#ifndef _GUI_ENUMTC1602WINDOWSTATE_H_
#define _GUI_ENUMTC1602WINDOWSTATE_H_
#include <cinttypes>
namespace GUI
{
    enum EnumTC1602WindowState : uint8_t
    {
        TC1602_WINDOW_STATE_ERROR_WINDOW = 0,
        TC1602_WINDOW_STATE_MAIN_WINDOW = 1,
        TC1602_WINDOW_STATE_MENU_WINDOW = 2,
        TC1602_WINDOW_STATE_TEMPERATURE_SET_WINDOW = 3,
        TC1602_WINDOW_STATE_HUMIDITY_SET_WINDOW = 4,
        TC1602_WINDOW_STATE_MAX_TEMPERATURE_ADJUSTING_VALUE = 5,
        TC1602_WINDOW_STATE_MIN_TEMPERATURE_ADJUSTING_VALUE = 6,
        TC1602_WINDOW_STATE_MAX_HUMIDITY_ADJUSTING_VALUE = 7,
        TC1602_WINDOW_STATE_MIN_HUMIDITY_ADJUSTING_VALUE = 8,
        TC1602_WINDOW_STATE_RESET,
        TC1602_WINDOW_STATE_SIZE
    };
} // namespace GUI

#endif // _GUI_ENUMTC1602WINDOWSTATE_H_