#ifndef _GUI_ENUMTC1602WINDOWSTATE_H_
#define _GUI_ENUMTC1602WINDOWSTATE_H_
namespace GUI
{
    enum EnumTC1602WindowState
    {
        TC1602_WINDOW_STATE_ERROR_WINDOW = 0,
        TC1602_WINDOW_STATE_MAIN_WINDOW = 1,
        TC1602_WINDOW_STATE_MENU_WINDOW = 2,
        TC1602_WINDOW_STATE_TEMPERATURE_SET_WINDOW = 3,
        TC1602_WINDOW_STATE_RESET,
        TC1602_WINDOW_STATE_SIZE
    };
} // namespace GUI

#endif // _GUI_ENUMTC1602WINDOWSTATE_H_